version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>   # filled in by the CodePipeline CodeDeployToECS action
        LoadBalancerInfo:
          ContainerName: dashboard
          ContainerPort: 8080
